# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-22 12:36
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Integration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('capabilities_url', models.URLField()),
                ('room_id', models.IntegerField()),
                ('group_id', models.IntegerField()),
                ('oauth_id', models.UUIDField()),
                ('oauth_secret', models.CharField(max_length=255)),
            ],
        ),
    ]
