# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-23 15:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('django_rest_hipchat', '0003_auto_20161123_1408'),
    ]

    operations = [
        migrations.CreateModel(
            name='Webhook',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event', models.CharField(choices=[('room_message', 'room_message')], max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('pattern', models.CharField(blank=True, max_length=255, null=True)),
                ('integration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhooks', to='django_rest_hipchat.Integration')),
            ],
        ),
    ]
