# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-01 07:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_rest_hipchat', '0005_installation_uninstalled'),
    ]

    operations = [
        migrations.AddField(
            model_name='installation',
            name='integration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='installations', to='django_rest_hipchat.Integration'),
        ),
    ]
